### ISSUE TITLE
Crash when loading undersize ROM 

### ISSUE THREAD

**Issue by pinobatch** [zeta0134/rusticnes-core#11]
The "beakers" ROM in [little things v20.10](https://github.com/pinobatch/little-things-nes/releases/v20.10) claims to be 16K+8K, but it's actually only 16K+4K. This admittedly invalid ROM crashes the emulator:
```
thread 'main' panicked at 'range end index 24592 out of range for slice of length 20496', /home/pino/.cargo/git/checkouts/rusticnes-core-c88980c8db510ad9/a2a9da8/src/cartridge.rs:118:20
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   1: core::panicking::panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
   2: core::slice::index::slice_end_index_len_fail
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/slice/index.rs:41
   3: rusticnes_core::cartridge::load_from_cartridge
   4: rusticnes_core::nes::NesState::from_rom
   5: rusticnes_sdl::game_window::GameWindow::open_file
   6: rusticnes_sdl::main
```

**Comment by zeta0134** [comment]
This is now somewhat corrected as of 47b6230bc477e2771e371a85f3c3e16c2698c0ce. RusticNES refuses to load the ROM (as it should, it is invalid) but instead of crashing, now dumps the following slightly unhelpful message to stdout:
```
Cartridge /home/zeta0134/Github/rusticnes-sdl/tests/little-things-nes-20.10/beakers/beakers.nes could not be played: Unable to open file as any known type, giving up.
ines: Error reading cartridge: failed to fill whole buffer
```
This should occur when attempting to read any undersized `.nes` file, regardless of the contents of the header. Note that if you attempt to load a header which specifies the maximum 58,720,256 TB of PRG ROM, your workstation is likely to run out of RAM well before it reaches the end of the file.
